package displayclient;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.4.2
//
// Created by Quasar Development at 28-02-2015
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class XmdsxmdsBinding
{
    interface XmdsIWcfMethod
    {
        XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://localhost/xibo";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    public XmdsxmdsBinding(){}

    public XmdsxmdsBinding(String url)
    {
        this.url = url;
    }

    public XmdsxmdsBinding(String url,int timeOut)
    {
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected XmdsExtendedSoapSerializationEnvelope createEnvelope()
    {
        XmdsExtendedSoapSerializationEnvelope envelope= new XmdsExtendedSoapSerializationEnvelope(XmdsExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,XmdsExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,XmdsExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public String RegisterDisplay(final String serverKey,final String hardwareKey,final String displayName,final String clientType,final String clientVersion,final Integer clientCode,final String operatingSystem,final String macAddress ) throws java.lang.Exception
    {
        return (String)execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "RegisterDisplay");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="displayName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(displayName!=null?displayName:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="clientType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(clientType!=null?clientType:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="clientVersion";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(clientVersion!=null?clientVersion:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="clientCode";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(clientCode!=null?clientCode:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="operatingSystem";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(operatingSystem!=null?operatingSystem:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="macAddress";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(macAddress!=null?macAddress:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("ActivationMessage");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"urn:xmds#RegisterDisplay");
    }
    
    public String RequiredFiles(final String serverKey,final String hardwareKey ) throws java.lang.Exception
    {
        return (String)execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "RequiredFiles");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("RequiredFilesXml");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"urn:xmds#RequiredFiles");
    }
    
    public byte[] GetFile(final String serverKey,final String hardwareKey,final Integer fileId,final String fileType,final Double chunkOffset,final Double chuckSize ) throws java.lang.Exception
    {
        return (byte[])execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "GetFile");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="fileId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(fileId!=null?fileId:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="fileType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(fileType!=null?fileType:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="chunkOffset";
                __info.type=Double.class;
                __info.setValue(chunkOffset!=null?chunkOffset:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="chuckSize";
                __info.type=Double.class;
                __info.setValue(chuckSize!=null?chuckSize:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object j = __soap.getProperty("file");
                return XmdsHelper.getBinary(j,false);
            }
        },"urn:xmds#GetFile");
    }
    
    public String Schedule(final String serverKey,final String hardwareKey ) throws java.lang.Exception
    {
        return (String)execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "Schedule");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("ScheduleXml");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"urn:xmds#Schedule");
    }
    
    public Boolean BlackList(final String serverKey,final String hardwareKey,final Integer mediaId,final String type,final String reason ) throws java.lang.Exception
    {
        return (Boolean)execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "BlackList");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="mediaId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(mediaId!=null?mediaId:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="type";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(type!=null?type:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="reason";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(reason!=null?reason:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("success");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"urn:xmds#BlackList");
    }
    
    public Boolean SubmitLog(final String serverKey,final String hardwareKey,final String logXml ) throws java.lang.Exception
    {
        return (Boolean)execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "SubmitLog");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="logXml";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(logXml!=null?logXml:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("success");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"urn:xmds#SubmitLog");
    }
    
    public Boolean SubmitStats(final String serverKey,final String hardwareKey,final String statXml ) throws java.lang.Exception
    {
        return (Boolean)execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "SubmitStats");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="statXml";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(statXml!=null?statXml:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("success");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"urn:xmds#SubmitLog");
    }
    
    public Boolean MediaInventory(final String serverKey,final String hardwareKey,final String mediaInventory ) throws java.lang.Exception
    {
        return (Boolean)execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "MediaInventory");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="mediaInventory";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(mediaInventory!=null?mediaInventory:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("success");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"urn:xmds#MediaInventory");
    }
    
    public String GetResource(final String serverKey,final String hardwareKey,final Integer layoutId,final String regionId,final String mediaId ) throws java.lang.Exception
    {
        return (String)execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "GetResource");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="layoutId";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(layoutId!=null?layoutId:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="regionId";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(regionId!=null?regionId:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="mediaId";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(mediaId!=null?mediaId:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("resource");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"urn:xmds#GetResource");
    }
    
    public Boolean NotifyStatus(final String serverKey,final String hardwareKey,final String status ) throws java.lang.Exception
    {
        return (Boolean)execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "NotifyStatus");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="status";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(status!=null?status:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("success");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"urn:xmds#NotifyStatus");
    }
    
    public Boolean SubmitScreenShot(final String serverKey,final String hardwareKey,final byte[] screenShot ) throws java.lang.Exception
    {
        return (Boolean)execute(new XmdsIWcfMethod()
        {
            @Override
            public XmdsExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              XmdsExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:xmds", "SubmitScreenShot");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="serverKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serverKey!=null?serverKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="hardwareKey";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(hardwareKey!=null?hardwareKey:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="screenShot";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(screenShot!=null?org.kobjects.base64.Base64.encode(screenShot):SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(XmdsExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("success");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"urn:xmds#SubmitScreenShot");
    }

    
    protected java.lang.Object execute(XmdsIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        XmdsExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    //android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    //android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
        

    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,XmdsExtendedSoapSerializationEnvelope envelope)
    {
        return new java.lang.Exception(fault.faultstring);
    }
}


